#!/usr/bin/env bash

# ---------------------------------------------------------------------
#  wipbak
#
#  Work-in-progress backup script.
#
#  Put this script in a directory that is in the PATH.  For example,
#  if this script is in a 'bin' directory under the home directory,
#  add this to .bashrc:
#    export PATH=$PATH:$HOME/bin
#
#  To use this script, the directory where it is to be run must have:
#  1. A file named 'wipbak-list.txt' that contains the names of files
#     for which backup copies are to be made.
#  2. A sub-directory named '_0_bak' where the copies will be placed.
#
# ---------------------------------------------------------------------


VERSION="2024.01.1"

LISTFILE="wipbak-list.txt"

BAKDIR="_0_bak"

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

VERBOSE=


function bakwip
{
    dt="$1"

    # xargs removes leading and trailing spaces.
    wip=$(echo "$2" | xargs)

    if [[ -z "$wip" ]]; then
        # Skip empty lines in list file.
        return
    fi

    if [ ! -e "$wip" ]; then
        printf "\nERROR: File not found: '%s'\n" "$wip"
        printf "Make sure %s is up to date.\n\n" "$LISTFILE"
        exit 1
    fi
    
    printf "'%s' " "$wip"

    pattern="/${wip//./\\.}\.[0-9]{8}_[0-9]{6}\.bak"

    if [ "$VERBOSE" ]; then
        printf "\n  Pattern: '%s'\n" "$pattern"
    fi

    prevbak=$(find ./${BAKDIR} -maxdepth 1 -type f | grep -P "${pattern}" | sort -r | head -n1)

    if [ -z "${prevbak}" ]; then
        printf "\n  No previous backup.\n"
    else
        if [ "$VERBOSE" ]; then
            printf "\n  Previous backup: '%s'\n" "$prevbak"
        fi
        diffresult=$(diff -q "${prevbak}" "${wip}")
        if [ -z "${diffresult}" ]; then
            printf "(same)\n"
            return
        else
            printf "\n"
        fi
    fi
    bak="./_0_bak/${wip}.${dt}.bak"
    printf "  Copy to %s\n" "$bak"
    cp "$wip" "$bak"
    chmod 400 "$bak"
}

printf "\nwipbak (version %s)\n\n" "$VERSION"

while getopts 'v' OPT
do
    case $OPT in
        v)  VERBOSE=1
            ;;
        ?)  printf "Usage: wipbak [-v]\nWhere: -v = Verbose.\n\n"
            exit 2
            ;;
    esac
done

if [ ! -e "./${LISTFILE}" ]; then
    printf "\nList file '%s' not found in current directory.\n" "$LISTFILE"
    exit 1
fi

if [ ! -d "./${BAKDIR}" ]; then
    printf "\nBackup directory '%s' not found in current directory.\n" "$BAKDIR"
    exit 1
fi

while IFS= read -r filename
do
    bakwip "$TIMESTAMP" "$filename"
done < "$LISTFILE"

printf "\n"
read -t7 -n1 -r -p "Press [Enter] to continue (or wait for timeout). "
printf "\n\nListing files in %s (most recent last):\n" "$BAKDIR"

ls -tr1 "./${BAKDIR}"
